### ISSUE TITLE
Package ‘dired+-’ is unavailable Error (use-package): Cannot load dired+

### ISSUE THREAD

**Issue by peng051410** [zamansky/using-emacs#4]
I use your config to launch emacs, i got an error:
![image](https://user-images.githubusercontent.com/5512326/35842414-e86810cc-0b3c-11e8-9d45-41f2390c5f0d.png)
and i try to install the dired+ package, the package not in the melpa repo, what should i do ?

**Comment by zamansky** [comment]
Yeah - melpa stopped indexing the code on the Emacs wiki so dired+ and a
bunch of other packages got lost.

It seems that most are being restored somewhere but not dired+.

Since the other packages I've used seemed to reappear I'm just waiting to
see if dired+ does as well since it's not essential to me and if it doesn't
I'll just have to see where it's living these days.

Mike


http://cestlaz.github.com
